on:
  push:
    branches: main

name: Render

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - run: |
          quarto --version
        
      - name: Render Quarto
        uses: quarto-dev/quarto-actions/render@v2
